# Generated by Django 3.2.25 on 2026-03-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20260313_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroAcesso',
            new_name='Acesso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
    ]
