# Generated by Django 3.2.25 on 2026-03-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20260316_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='ativo',
        ),
    ]
